### ISSUE TITLE
ADOT New Relic OTLP Support

### ISSUE THREAD

**Issue by caiges** [aws-observability/aws-otel-collector-test-framework#327]
New Relic has verified OTLP support using the ADOT collector.

Customers exporting [OTLP data to New Relic](https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start/) via our [early access program](https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start/#export) can use an [exporter configuration](https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start/#collector) pointing at the New Relic OTLP endpoint along with a New Relic ingest license key:

```yaml
...

exporters:
  otlp:
    endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
    headers:
      api-key: ${NEW_RELIC_LICENSE_KEY}

...
```

New Relic is in the process of validating OTLP histogram support and we'll update our progress in the coming weeks.
