### ISSUE TITLE
ADOT Sumo Logic OTLP HTTP Support

### ISSUE THREAD

**Issue by mat-rumian** [aws-observability/aws-otel-collector-test-framework#333]
[Sumo Logic](https://help.sumologic.com/Traces/Getting_Started_with_Transaction_Tracing/Set_up_traces_collection_for_AWS_environments) has verified OTLP HTTP support using the ADOT collector in version [v0.11.0](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.11.0)
```
exporters:
  otlphttp:
    endpoint: ${SUMO_HTTP_TRACES_URL}
```

Sumo Logic recommends to use `batch` processor in case of sending data.

```
processors:
  batch/traces:
    timeout: 5s
    send_batch_size: 512
```
