### ISSUE TITLE
ADOT Lightstep OTLP Support

### ISSUE THREAD

**Issue by smithclay** [aws-observability/aws-otel-collector-test-framework#337]
Lightstep has verified OTLP support using the ADOT collector `v0.12.0`.

Lightstep customers using [public satellites](https://docs.lightstep.com/docs/about-public-satellites) can send traces to Lightstep using the OTLP exporter with the following configuration using a [Lightstep Access Token](https://docs.lightstep.com/docs/create-and-manage-access-tokens):

```
...
exporters:
  otlp:
    endpoint: ingest.lightstep.com:443
    headers:
      "lightstep-access-token": "${LS_ACCESS_TOKEN}"
...
```
