### ISSUE TITLE
ADOT Dynatrace OTLP support 

### ISSUE THREAD

**Issue by arminru** [aws-observability/aws-otel-collector-test-framework#339]
Dynatrace has verified OTLP support using the ADOT collector.

Dynatrace users can use the OTLP/HTTP exporter to send OpenTelemetry trace data to our OTLP Trace Ingest API.
The documentation can be found here: https://www.dynatrace.com/support/help/how-to-use-dynatrace/transactions-and-services/purepath-distributed-traces/opentelemetry-ingest/
Here is a full example on how to configure ADOT to send traces to our endpoint:
https://www.dynatrace.com/support/help/how-to-use-dynatrace/transactions-and-services/purepath-distributed-traces/opentelemetry-ingest/how-to-lambda/

The exporter endpoint configuration should look as follows:
```
...
exporters:
  otlphttp:
    endpoint: "https://${DYNATRACE_TENANT_ID}.live.dynatrace.com/api/v2/otlp"
    headers:
      "Authorization": "Api-Token ${DYNATRACE_API_TOKEN}"
...
```
