### ISSUE TITLE
ADOT Honeycomb OTLP support

### ISSUE THREAD

**Issue by MikeGoldsmith** [aws-observability/aws-otel-collector-test-framework#341]
Honeycomb has verified OTLP support using the ADOT collector `v0.12.0`.

Honeycomb customers can send traces to Honeycomb using the OTLP exporter with the following configuration using a Honeycomb API key and dataset:

```
exporters:
otlp:
  endpoint: "api.honeycomb.io:443"
  headers:
    "x-honeycomb-team": "{API_KEY}"
    "x-honeycomb-dataset": "{DATASET}"
```

We have additional information for configuring the Collector to work with Honeycomb too:
https://docs.honeycomb.io/getting-data-in/opentelemetry/otel-collector/
