### ISSUE TITLE
ADOT Appdynamics OTLP support

### ISSUE THREAD

**Issue by ajinkyak26** [aws-observability/aws-otel-collector-test-framework#343]
Appdynamics has verified OTLP support using the ADOT collector [v.0.12.0](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.12.0) and collector and contrib [v.0.35.0](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.35.0) 

Appdynamics customers can send traces using the OTLP exporter with the following configuration using an x-api-key
```
exporters:
     otlphttp:
        endpoint: "<appdynamics-endpoint>"
        headers: {"x-api-key": "secret-api-key"}
```

More details can be found out here regarding the configuration
https://docs.appdynamics.com/21.9/en/application-monitoring/ingest-opentelemetry-trace-data
